services:
  web:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/data 
      && chmod -R 755 /var/www/html/data 
      && docker-php-entrypoint apache2-foreground"